name: FIRSTDBTEST

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
 
      - name: Test 🚨
        run: npm test
        
      - name: Run a one-line script
        run: echo "Hello, FIRSTDBTEST!"